# Generated by Django 6.0.5 on 2026-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='location_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
